spring:
  config:
    import:
      - classpath:/application.common.yaml
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}

app:
  jwt:
    key: ${JWT_KEY}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_CALLBACK_URL}
  seoul-data:
    key: ${SEOUL_DATA_API_KEY}